[tool.poetry]
name = "zp"
version = "0.1.0"
description = ""
authors = ["yunus"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "^2.25.1"
openpyxl = "^3.1.2"
pandas = "^2.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
